### ISSUE TITLE
Discussions for suspense

### ISSUE THREAD

**Issue by kael** [bvaughn/suspense#8]
It'd be nice if we could discuss about `suspense` on GitHub with some ideas, features requests or usage questions.

Would you please open the _Discussions_ section of this repo ?

Awesome library, thanks. :+1:

Cheers

**Comment by bvaughn** [comment]
I'll try turning this on to see how it goes, but I'm not sure how I feel about it because it seems like it would potentially need more time from me (to monitor and participate in discussions) than I have available at the moment.

**Comment by kael** [comment]
Alrighty.

Some ideas :
- use `suspense` in Web Workers similarly to Dexie.js [`liveQuery()`](https://dexie.org/docs/liveQuery()) which allows to write data to IndexedDB in a web worker and have data dispatched on the main thread using a hook (by using `BrodcastChannel`)

- use `suspense` to easily attach streams and pipe data, like or perhaps with [`remote-web-streams`](https://github.com/MattiasBuelens/remote-web-streams) which allows to pipe data from a web worker to the main thread using streams.

(I'm assuming that web worker and streams are a fancy combination for loading large sets of data the less blocking way)

- virtual scrolling integration, combining streams and cache, for scrolling large lists, similar to [`hyperlist`](https://github.com/tbranyen/hyperlist).

Cheers.
